python cli/run_t5_mlm_flax.py \
    --model_type t5 \
    --config_name configs/t5-small-4L-8H \
    --tokenizer_name t5-small \
    --cache_dir /home/kzhao/.cache/huggingface/ \
    --dataset_pickle_path processed_realnewslike.pkl \
    --max_seq_length 128 \
    --preprocessing_num_workers 16 \
    --layer_norm_position Post-Norm \
    --layer_norm_type vanilla \
    --position_embed BERT \
    --output_dir t5_pretraining_1 \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --per_device_train_batch_size 128 \
    --per_device_eval_batch_size 128 \
    --learning_rate 0.002 \
    --weight_decay 0.001 \
    --adafactor \
    --num_train_epochs 1 \
    --warmup_steps 16000 \
    --save_steps 8000 \
    --eval_steps 4000 \
    --logging_steps 40
