python cli/run_t5_mlm_flax.py \
    --model_type bart \
    --config_name facebook/bart-base \
    --tokenizer_name facebook/bart-base \
    --cache_dir /home/kzhao/.cache/huggingface/ \
    --dataset_pickle_path processed_realnewslike_bart.pkl \
    --max_seq_length 128 \
    --preprocessing_num_workers 16 \
    --output_dir t5_pretraining_bart \
    --overwrite_output_dir \
    --do_train \
    --do_eval \
    --per_device_train_batch_size 256 \
    --per_device_eval_batch_size 256 \
    --learning_rate 0.003 \
    --weight_decay 0.001 \
    --adafactor \
    --num_train_epochs 1 \
    --warmup_steps 8000 \
    --save_steps 4000 \
    --eval_steps 2000 \
    --logging_steps 20
